### ISSUE TITLE
Qualtrics Junior Scrum Master and volunteers draft a sample survey

### ISSUE THREAD

**Issue by colemane22** [colemane22/QMB-Group1#1]
Draft a 15 question sample survey about our topic school sports/ on-campus involvement in Qualtrics and share it with me. My email for Qualtrics is ethan.coleman@spartans.ut.edu.

**Comment by nataliemantras** [comment]
Do you know if the survey questions have to be "yes or no" or are they like " on a scale of 1-5"? Or can it be a mix? If you aren't sure I can email Jerry and ask @colemane22
