### ISSUE TITLE
Send out the survey link below to 10 different people by our next meeting

### ISSUE THREAD

**Issue by colemane22** [colemane22/QMB-Group1#2]
https://qualtricsxm972ztd9zs.qualtrics.com/jfe/form/SV_3CAMRbXeQ7ujW8C

**Comment by paolo423** [comment]
sent it in a group chat with 12 people 

-Paolo

**Comment by nataliemantras** [comment]
I sent out the survey to 11 people - Natalie Mantras

**Comment by Serenaolden** [comment]
Sent it to 10 people! -Serena Olden

**Comment by kailamiles** [comment]
Sent in my sorority group chat with 150 people

**Comment by kprime245** [comment]
Sent it to 10 people

**Comment by joshsentell** [comment]
Sent to 10 people

**Comment by taylorhughes804** [comment]
Sent it to 10 people

**Comment by emilylazarz** [comment]
sent it to 10 people
